services:
  pytorch_241:
    build:
      context: .
      dockerfile: .docker/nvidia-cuda-12.4.1-ubuntu22.04.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
